AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceBeforeFirstArg:
  Include:
    - db/migrate/*.rb
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/rspec/*.rb

Metrics/ModuleLength:
  Exclude:
    - spec/rspec/*.rb
